### ISSUE TITLE
Calculate Cubic Ft. for a box

### ISSUE THREAD

**Issue by jwelbs** [RockefellerArchiveCenter/MatchBox#30]
MatchBox provides all the measurements required to calculate the cubic footage of a box. 
RAC staff adding instances to ArchivesSpace need to know cubic footage for their projects.
Currently, ArchivesSpace does not calculate cubic footage.
I suggest we add a simple cubic feet calculator to the bottom of MatchBox that anyone can use since they will already have the application open when finding a correct box. 

Anyone interested?

**Comment by helrond** [comment]
As per discussions on Slack, we'll add an additional column which calculates cubic feet for each container profile.
