### ISSUE TITLE
Freeze top row of table

### ISSUE THREAD

**Issue by EcZX** [RockefellerArchiveCenter/MatchBox#35]
## Is your feature request related to a problem? Please describe.
When you scroll down with too many results, the top row goes away which result in scrolling back and forth to understand what is depth, height, etc.

## Describe the solution you'd like
Is there a way to freeze the top row, moves vertically or in sync.

## Additional context
Feel free to disagree but it seems like a lot of moving back and forth.

**Comment by helrond** [comment]
@EcZX you'll have to clear your browser cache to make this work.

**Comment by EcZX** [comment]
@helrond Thanks so much! This helps solve the issue of scrolling back and forth.
