### ISSUE TITLE
Changing the preferred boxes 

### ISSUE THREAD

**Issue by EcZX** [RockefellerArchiveCenter/MatchBox#40]
## Is your feature request related to a problem? Please describe.
I noticed that all of the boxes in Matchbox have preferred check mark next to them and verified this with a few staff members.

## Describe the solution you'd like
Is there a way to revert this back to the select few that are preferred? 

## Additional context
Matchbox view using Google Chrome

![screenshot11](https://user-images.githubusercontent.com/28789468/69184014-05896b00-0ae2-11ea-9578-704f958d210b.PNG)

**Comment by helrond** [comment]
Thanks for reporting this @EcZX! This is definitely something that falls into the category of a bug. Fix coming shortly.
