### ISSUE TITLE
Error Loading Data in Matchbox

### ISSUE THREAD

**Issue by eswanson611** [RockefellerArchiveCenter/MatchBox#41]
## Describe the bug
Matchbox is experiencing an issue loading data. The error message indicates an issue connecting to AS which is running fine in a separate browser and credentials are up to date.

## To reproduce
1. Go to 'http://matchbox.rockarch.org/' (attempted using Chrome and Firefox)
2. See error "Make sure ArchivesSpace is running and your credentials are correct"

## Expected behavior
A list of all container profile data available in AS.

## Impact on your work
The data displayed in Matchbox is helpful for completing the extent portion of an accession record.

**Comment by helrond** [comment]
Hi @eswanson611 thanks for reporting this. The authentication token used to access the ArchivesSpace API had expired, so I just updated that. You may have to clear your browser cache but this should be fixed. Please reopen this issue if it's not!

**Comment by eswanson611** [comment]
Thank you, @helrond ! It works like a charm.
